name: Run manually

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - name: Run Committee
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: npx ts-node ./src/index.ts
      - name: Run Council
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: npx ts-node ./src/council.ts
