name: Run

on:
  schedule:
    - cron: "30 14 1-7 * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - name: Run
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: bash ./run.sh
